name: database_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Versioning information
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.1
  shared_preferences: ^2.5.1
  decimal: ^3.2.1
  intl: ^0.20.1
  get: ^4.6.6
  pinput: ^5.0.1
  google_fonts: ^6.2.1

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icons/tracking_truck.png"

flutter:
  # Ensures that Material Icons are available
  uses-material-design: true

  # To add assets to your application, uncomment and add paths here:
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # Custom fonts can be added here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
