// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WUsL2_EdOs3GJyfrbtSKdUOaYVGoehU',
    appId: '1:1031420983105:web:c7abefad1090069f0993c0',
    messagingSenderId: '1031420983105',
    projectId: 'trip-sheet-entry',
    authDomain: 'trip-sheet-entry.firebaseapp.com',
    storageBucket: 'trip-sheet-entry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBStAA0kz3xr3bqMTZV6HX-70zvdTkps-E',
    appId: '1:1031420983105:android:0f69ad8c88ed748e0993c0',
    messagingSenderId: '1031420983105',
    projectId: 'trip-sheet-entry',
    storageBucket: 'trip-sheet-entry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGp33p0HrOauA2LJc1Txvytgl0Obfkow',
    appId: '1:1031420983105:ios:98ec55e7d2ed33aa0993c0',
    messagingSenderId: '1031420983105',
    projectId: 'trip-sheet-entry',
    storageBucket: 'trip-sheet-entry.firebasestorage.app',
    iosBundleId: 'com.example.databaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGp33p0HrOauA2LJc1Txvytgl0Obfkow',
    appId: '1:1031420983105:ios:98ec55e7d2ed33aa0993c0',
    messagingSenderId: '1031420983105',
    projectId: 'trip-sheet-entry',
    storageBucket: 'trip-sheet-entry.firebasestorage.app',
    iosBundleId: 'com.example.databaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-WUsL2_EdOs3GJyfrbtSKdUOaYVGoehU',
    appId: '1:1031420983105:web:2f53cb674fdd3d210993c0',
    messagingSenderId: '1031420983105',
    projectId: 'trip-sheet-entry',
    authDomain: 'trip-sheet-entry.firebaseapp.com',
    storageBucket: 'trip-sheet-entry.firebasestorage.app',
  );
}
